In [3]:
import numpy as np

In [21]:
def rolling_window(big, small):
    r, c=0, 0
    new=np.zeros((big.shape[0]-small.shape[0]+1,big.shape[0]-small.shape[0]+1),dtype=int)
    print new.shape[0]
    for i in range(new.shape[0]):
        temp=0
        for j in range(new.shape[1]):
            window=big[r:r+new.shape[0],c:c+new.shape[1]]
            temp=np.sum(small*window)
            new[i][j]=temp
            c+=1 
        r+=1 
        c=0
    return new

In [22]:
big=np.random.randint(10,size=(3,3))
small=np.random.randint(10,size=(2,2))
print big
print small
rolling_window(big,small)

[[7 8 5]
 [5 3 6]
 [1 8 2]]
[[2 9]
 [9 5]]
2


array([[146, 118],
       [ 86, 142]])