In [124]:
import numpy as np

In [125]:
def mul(big_m, small_m):
    r=c= big_m.shape[0] - small_m.shape[0] + 1
    new_m = np.zeros((r,c))
    print(new_m.shape)
    for x in range(new_m.shape[0]):
        for y in range(new_m.shape[1]):
            d = big_m[x:small_m.shape[0]+x, y:small_m.shape[0]+y]
            for i in range(small_m.shape[0]):
                for j in range(small_m.shape[1]):
                    new_m[x,y] += d[i,j] * small_m[i,j]
            
    return new_m

In [126]:
mat1 = np.ones((5,5))
mat2 = np.array([[1,2], [2,1]])

In [127]:
print(mul(mat1,mat2))

(4, 4)
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]
