In [76]:
import numpy as np

In [77]:
m1 = np.array([[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5]])
m2 = np.array([[1,1],[1,1]])

In [78]:
def shape(m1, m2):
    m3_shape1 = np.subtract(np.array(m1.shape), np.array(m2.shape))
    m3_shape = np.add(m3_shape1, np.array([1,1]))
    #print(m3_shape)
    return m3_shape

In [79]:
def matrix_mul(m1, m2):
    m3_shape = shape(m1, m2)
    m3 = np.zeros(m3_shape)
    x = m2.shape[0]
    y = m2.shape[1]
    #print(m3)
    for j in range(m3.shape[0]):
        for i in range(m3.shape[1]):
            temp = m1[j:j+x, i:i+y]
            m3[j][i] = np.sum(np.multiply(temp,m2))
    return m3

In [80]:
print(matrix_mul(m1,m2))

[[20. 20. 20. 20.]
 [20. 20. 20. 20.]
 [20. 20. 20. 20.]
 [20. 20. 20. 20.]]
