In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [23]:
l=[[2,3,1,1],[4,2,1,2],[1,3,2,3],[0,1,2,4]]
m=[[1,2],[3,4]]

In [24]:
l=np.array(l)
m=np.array(m)
x,y=m.shape
print m[1][0]
print x,y

3
2 2


In [25]:
def multiply(big_matrix,small_matrix):
    x=small_matrix.shape[0]
    y=big_matrix.shape[0]
    sh=y-x+1
    mat=np.zeros((sh,sh))
    for i in range(sh):
        for j in range(sh):
            row=i
            col=j
            sum1=0.0
            for k in range(small_matrix.shape[0]):
                for l in range(small_matrix.shape[1]):
                    sum1+=(small_matrix[k][l]*big_matrix[row][col])
                    col+=1
                row+=1
                col=j
            mat[i][j]=sum1
    return mat
                    
                    
                    
    
   
            
    

In [26]:
print multiply(l,m)

[[28. 15. 14.]
 [23. 21. 23.]
 [11. 18. 30.]]
