In [7]:
import numpy as np

In [8]:
k_width=2
k_height=2

data_width=3
data_height=4

kernel=np.random.randint(1,5,(k_width,k_height))
data=np.random.randint(1,5,(data_width,data_height))

In [9]:
print(kernel)

[[2 1]
 [1 1]]


In [10]:
print(data)

[[3 2 1 2]
 [1 3 1 2]
 [2 4 3 1]]


In [11]:
def kernel_mult(kernel,data):
    final=[]
    k_height=kernel.shape[0]
    k_width=kernel.shape[1]
    for i in range(data.shape[0]-k_height+1):
        ele=[]
        for j in range(data.shape[1]-k_width+1):
            ele1=data[i:i+k_height,j:j+k_height]
            prod=ele1*kernel
            ele.append(prod.sum())
        final.append(ele)
    return final

In [12]:
kernel_mult(kernel,data)

[[12, 9, 7], [11, 14, 8]]