In [14]:
import numpy as np

In [19]:
def mul(input1,input2):
    output=np.zeros((input2.shape[0]-input1.shape[0]+1,input2.shape[0]-input1.shape[1]+1))
    for i in range(input2.shape[0]-input1.shape[0]+1):
        for j in range(input2.shape[1]-input1.shape[1]+1):
            for s in range(input1.shape[0]):
                for t in range(input1.shape[1]):
                    output[i][j]+=input2[i+s][j+t]*input1[s][t]
                    
    return output    


In [20]:
input1=np.array([[1,5],[2,3]])
input2=np.array([[2,4,6,8],[1,3,5,7],[2,1,5,1],[3,7,8,3]])
x=mul(input1,input2)
print(x)

[[33. 55. 77.]
 [23. 45. 53.]
 [34. 64. 35.]]
